### ISSUE TITLE
Error building tor-0.4.4.7

### ISSUE THREAD

**Issue by svengo** [svengo/docker-tor#5]
tor 0.4.4.7 fails to build using alpine 3.13.1 (latest) and libressl 3.1.5. 
Reported as tor issue: https://gitlab.torproject.org/tpo/core/tor/-/issues/40278.

```
$ docker build .
[...]
  CC       src/lib/tls/libtor_tls_a-tortls_openssl.o
In file included from /usr/include/openssl/bio.h:69,
                 from /usr/include/openssl/evp.h:67,
                 from /usr/include/openssl/hmac.h:67,
                 from /usr/include/openssl/ssl.h:150,
                 from src/lib/tls/tortls_openssl.c:48:
/usr/include/openssl/crypto.h:335:39: error: macro "OpenSSL_version_num" passed 1 arguments, but takes just 0
  335 | unsigned long OpenSSL_version_num(void);
      |                                       ^
In file included from src/lib/tls/tortls_openssl.c:34:
./src/lib/crypt_ops/compat_openssl.h:37: note: macro "OpenSSL_version_num" defined here
   37 | #define OpenSSL_version_num() SSLeay()
      |
make[1]: *** [Makefile:17838: src/lib/tls/libtor_tls_a-tortls_openssl.o] Error 1
make[1]: Leaving directory '/tmp/tor-0.4.4.7'
make: *** [Makefile:7156: all] Error 2
```
